# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 11:23
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Vrijednost')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='kategorija')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
            options={
                'verbose_name': 'kategorija',
                'verbose_name_plural': 'kategorije',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('title', models.CharField(max_length=300, verbose_name='Naziv ponude')),
                ('summary', models.TextField(help_text='Unesite kratki opis vaše ponude', max_length=1000, verbose_name='Opis ponude')),
                ('id', models.CharField(default=uuid.uuid4, help_text='Unique ID for this particular offer', max_length=36, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Količina')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Objavljeno')),
                ('active', models.BooleanField(default=True)),
                ('measure', models.CharField(choices=[('kom', 'komad'), ('kg', 'kilogram'), ('h', 'sat')], default='kom', max_length=3, verbose_name='Jedinična mjera')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cijena po jedinici')),
                ('offer_pic', stdimage.models.StdImageField(default='images/offer_pics/no-img.jpg', help_text='Opcionalna fotografija uz vašu ponudu', upload_to='images/offer_pics', verbose_name='Fotografija')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Kategorija')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='PositiveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Vrijednost')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('transactions', models.ManyToManyField(to='app.Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='TextRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_rating', models.TextField(blank=True, help_text='Unesite vaše dojmove vezano uz korisnika odnosno robu/uslugu', max_length=1000, null=True, verbose_name='Ocjena')),
            ],
        ),
        migrations.CreateModel(
            name='TotalBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalLiability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Količina')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Provedeno')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OIB', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Unesite ispravni OIB', regex='^\\d{11}$')], verbose_name='OIB')),
                ('first_name', models.CharField(max_length=20, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=25, verbose_name='Prezime')),
                ('address', models.CharField(max_length=30, verbose_name='Adresa')),
                ('town', models.CharField(max_length=15, verbose_name='Mjesto')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Upišite ispravan broj telefona')], verbose_name='Telefon')),
                ('automatic_max', models.DecimalField(decimal_places=2, default=Decimal('300'), max_digits=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='textrating',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Transaction'),
        ),
        migrations.AddField(
            model_name='textrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='trans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Transaction'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
