# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='textrating',
            name='value',
            field=models.IntegerField(choices=[(1, 'Loše'), (2, 'Moglo bi i bolje'), (3, 'Zadovoljavajuće'), (4, 'Vrlo dobro'), (5, 'Odlično')], default=1, help_text='Ocijenite korisnika i preuzetu robu/uslugu od 1-5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textrating',
            name='text_rating',
            field=models.TextField(blank=True, help_text='Unesite vaše dojmove vezano uz korisnika odnosno robu/uslugu', max_length=1000, null=True, verbose_name='Komentar'),
        ),
    ]
