# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='summary',
            field=models.TextField(blank=True, help_text='Opcionalno recite nešto o sebi i proizvodima i uslugama koje nudite', max_length=1000, null=True, verbose_name='Kratki opis'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9\\s()_+-]+$', 'Upišite ispravan broj telefona')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=stdimage.models.StdImageField(default='images/profile_photos/no_photo.png', help_text='Opcionalna profilna fotografija', upload_to='images/profile_photos', verbose_name='Fotka'),
        ),
    ]
