# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171005_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='textrating',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
