# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_textrating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.TextField(blank=True, help_text='Adresa preuzimanja robe/usluge', max_length=500, null=True, verbose_name='Adresa preuzimanja'),
        ),
        migrations.AddField(
            model_name='offer',
            name='address_type',
            field=models.IntegerField(choices=[(1, 'Kućna adresa'), (2, 'Druga adresa')], default=1),
        ),
    ]
