# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171019_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positivebalance',
            old_name='type',
            new_name='_type',
        ),
        migrations.AddField(
            model_name='balance',
            name='_type',
            field=models.IntegerField(default=1),
        ),
    ]
