# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171019_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='quantity',
            new_name='start_quantity',
        ),
        migrations.AddField(
            model_name='balance',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='used_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Transaction'),
        ),
    ]
