# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171019_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='_type',
            new_name='balance_type',
        ),
        migrations.RenameField(
            model_name='positivebalance',
            old_name='_type',
            new_name='positivebalance_type',
        ),
    ]
