# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171019_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Naziv ponude'),
        ),
    ]
