# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171023_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum rođenja'),
        ),
    ]
